### ISSUE TITLE
[FEATURE] Support SRV records

### ISSUE THREAD

**Issue by Siphonay** [mocktools/ruby-dns-mock#120]
### New feature request checklist

- [x] I have updated `dns_mock` to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/mocktools/ruby-dns-mock/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://github.com/mocktools/ruby-dns-mock/blob/master/README.md)
- [x] I have searched for [existing GitHub issues](https://github.com/mocktools/ruby-dns-mock/issues)

### Feature description

I’m modifying a gem that works with DNS calls. One of these calls is fetching an SRV record. I would like to use ruby-dns-mock to write tests, but it doesn’t support SRV records. It’s a fairly common type of record and so I think it has its place in the scope of this project.

**Comment by bestwebua** [comment]
@Siphonay Thanks, good catch! I will add it to project road map 🍻

**Comment by bestwebua** [comment]
@Siphonay Hello! You feature request already in latest release ([1.6.0](https://github.com/mocktools/ruby-dns-mock/releases/tag/v1.6.0))

**Comment by Siphonay** [comment]
awesoe, thanks you for working on this so quick!

**Comment by bestwebua** [comment]
@Siphonay The best thanks is starrizing this repo 😺
