### ISSUE TITLE
[FEATURE] Logging of queries and responses

### ISSUE THREAD

**Issue by mroach** [mocktools/ruby-dns-mock#136]
### New feature request checklist

- [x] I have updated `dns_mock` to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/mocktools/ruby-dns-mock/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://github.com/mocktools/ruby-dns-mock/blob/master/README.md)
- [x] I have searched for [existing GitHub issues](https://github.com/mocktools/ruby-dns-mock/issues)

### Feature description

The basic goal is to have an instance of a DNS mock server be able to tell its hosting application which queries were made. This would allow writing a test to ensure that your code had the side effect of issuing an expected DNS query.

Some background on why I need this in particular:

We use [FQDN Network Policies](https://cloud.google.com/kubernetes-engine/docs/how-to/fqdn-network-policies) in our release environments to control egress. These work by creating a list of allowed names or name patterns, and then when the DNS server receives a query, it will add a firewall rule to permit the associated IP addresses with a TTL matching the DNS server's response.

For example if I whitelist `*.example.com` and our app queries `api.example.com`, the DNS server triggers a firewall allowance for its IP. This works great.

Where we ran into a problem is CNAMEs. Customers can and do use CNAMEs for permitted services so they have their own branding on them. e.g. `auth.corp.test CNAME corp.example.com`. We only whitelist `*.example.com` but the DNS query is for `auth.corp.test` which is not allowed so it doesn't get permitted.

Our solution to this was pre-resolving/chasing CNAMEs. By checking if `auth.corp.test` is a CNAME and then resolving its target recursively, we can solve for this.

### Implementation

I already created a working example of this. It's a small modification that creates an array instance variable in the mock server and pushes messages onto it when queries are made. That way in my tests I can be sure that our CNAME pre-chasing Faraday middleware is doing what it should be.

https://github.com/mocktools/ruby-dns-mock/compare/master...mroach:ruby-dns-mock:feature/query-log?expand=1

I hope this makes sense and would be considered a useful feature :)

**Comment by bestwebua** [comment]
Hi, @mroach! Thanks for your report and merge request. I will prepare new release till the end of this week.

**Comment by bestwebua** [comment]
This feature is available in the latest release.
