### ISSUE TITLE
[FEATURE] Binding to port 0 will tell the OS to assign you a port

### ISSUE THREAD

**Issue by ioquatix** [mocktools/ruby-dns-mock#42]
https://github.com/mocktools/ruby-dns-mock/blob/1d3a096e91c25c454e4323b8491f2e85f55f1dda/lib/dns_mock/server/random_available_port.rb#L8

It seems like this could be greatly simplified.

**Comment by bestwebua** [comment]
@ioquatix Thanks for your suggestion, Samuel! I'll simplify lib codebase with this solution in next release soon.

**Comment by bestwebua** [comment]
@ioquatix Done :)
