### ISSUE TITLE
[QUESTION] More usage infos

### ISSUE THREAD

**Issue by jonnynux** [mocktools/ruby-dns-mock#72]
### New question checklist

- [x] I have read the [Contribution Guidelines](https://github.com/mocktools/ruby-dns-mock/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://github.com/mocktools/ruby-dns-mock/blob/master/README.md)
- [x] I have searched for [existing GitHub issues](https://github.com/mocktools/ruby-dns-mock/issues)

### Question

Normally when I want to resolve an hostname I do `Resolv::DNS.new(nameserver: '1.1.1.1').getaddresses('one.one.one.one')`, but I cannot figure out how to do the same with this gem using the fake DNS instead a real one.

Thanks a lot.

**Comment by bestwebua** [comment]
Hello, @jonnynux! This solution comes from `dns_mock` gem documentation, it's pretty easy:

```ruby
require 'resolv'
require 'dns_mock'

dns_mock_server = DnsMock.start_server(records: { 'example.com' => { a: %w[1.1.1.1] } })
Resolv::DNS.new(nameserver_port: [['127.0.0.1', dns_mock_server.port]]).getaddresses('example.com') # => [#<Resolv::IPv4 1.1.1.1>]
```

**Comment by jonnynux** [comment]
Thanks a lot @bestwebua, my fault on Resolv::DNS.new syntax.
